# Changes here will be overwritten by Copier
_commit: v0.2.18
_src_path: git+https://gitlab.ewi.tudelft.nl/reit/python-package-template
email: sreeparna9324@gmail.com
environment_manager: uv
full_name: sree2712
host: github.com
license: MIT
min_python_version: '3.10'
org: sree2712
project_name: reit-py-course25
project_short_description: This is a minimal project for the hands-on tutorials.
python_name: reit_py_course25
url: https://github.com/sree2712/reit-py-course25
